image: gitpod/workspace-full

tasks:
  - before: npm install -g @leon-ai/cli
    init: >
      leon create birth --develop &&
      exec $SHELL
    command: leon start

ports:
  - port: 1337
    onOpen: notify

github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
    addComment: true
    addBadge: true
    addLabel: true
