name: Pre-release Python bridge

on: workflow_dispatch

env:
  PIPENV_PIPFILE: bridges/python/src
  PIPENV_VENV_IN_PROJECT: true

jobs:
  pre-release:
    name: Pre-release

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9.10
          # cache: pipenv

      - name: Install Pipenv
        run: pip install --upgrade pip && pip install pipenv

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: lts/*
          cache: npm

      - name: Set Python bridge version
        working-directory: bridges/python/src
        run: |
          echo "PYTHON_BRIDGE_VERSION=$(python -c "from version import __version__; print(__version__)")" >> $GITHUB_ENV
          echo "Python bridge version: ${{ env.PYTHON_BRIDGE_VERSION }}"

      - name: Install core
        run: npm ci

      - name: Setup Python bridge
        run: npm run setup:python-bridge

      - name: Build Python bridge
        run: npm run build:python-bridge

      - uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          automatic_release_tag: python-bridge_v${{ env.PYTHON_BRIDGE_VERSION }}
          draft: true
          prerelease: false
          title: Python Bridge ${{ env.PYTHON_BRIDGE_VERSION }}
          files: |
            bridges/python/dist/*.zip
