name: Tests

on:
  push:
    branches: [master, develop]
  pull_request:
    branches: [master, develop]

jobs:
  tests:

    runs-on: ubuntu-20.04
    container: leonai/ci:latest

    steps:
      - uses: actions/checkout@v2

      - name: Cache node_modules
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('package-lock.json') }}
          restore-keys: ${{ runner.os }}-npm-
      - name: Cache Pipenv
        uses: actions/cache@v2
        with:
          path: ./bridges/python/.venv
          key: ${{ runner.os }}-pip-${{ hashFiles('**/Pipfile.lock') }}
          restore-keys: ${{ runner.os }}-pip-
      - name: Install npm dependencies
        run: npm ci

      - name: Run JSON tests
        run: npm run test:json

      - name: Run E2E tests
        run: npm run test:e2e

      - name: Install offline STT
        run: npm run setup:offline-stt

      - name: Install offline TTS
        run: npm run setup:offline-tts

      - name: Run unit tests
        run: npm run test:unit
